const CITY_ALIASES: { [key: string]: string } = {
  almaty: 'Алматы',
  astana: 'Астана',
  shymkent: 'Шымкент',
  aqtau: 'Актау',
  aktobe: 'Актобе',
  atyrau: 'Атырау',
  balqash: 'Балхаш',
  zhezqazghan: 'Жезказган',
  taraz: 'Тараз',
  qyzylorda: 'Кызылорда',
  qostanai: 'Костанай',
  pavlodar: 'Павлодар',
  petropavl: 'Петропавловск',
  oskemen: 'Усть-Каменогорск',
  temirtau: 'Темиртау',
  turkistan: 'Туркестан',
  semei: 'Семей',
  oral: 'Уральск',
  kokshetau: 'Кокшетау',
  qonayev: 'Конаев',
  rudnyi: 'Рудный',
  zhezkazgan: 'Жезказган',
  ekibastuz: 'Экибастуз',
  karaganda: 'Караганда',
  satbayev: 'Сатпаев',
  saryagash: 'Сарыагаш',
  taldykorgan: 'Талдыкорган',
  kulsary: 'Кульсары',
  kandyagash: 'Кандыагаш',
  ayaguz: 'Аягоз',
  arkalyk: 'Аркалык',
  aksay: 'Аксай',
  shakhtinsk: 'Шахтинск',
  ayaguz: 'Аягуз',
  arkalyk: 'Аркалык',
  leninsk: 'Ленинск',
  kazakh: 'Казахск',
  qapshaghai: 'Капшагай',
  shchuchinsk: 'Щучинск',
  aksu: 'Аксу',
  zhanaozen: 'Жанаозен',
  kentau: 'Кентау',
  ridder: 'Риддер',
  stepnogorsk: 'Степногорск',
  abai: 'Абай',
  lisakovsk: 'Лисаковск',
  sarqan: 'Саркан',
  tekeli: 'Текели',
  zharkent: 'Жаркент',
  shchuchinsk: 'Щучинск',
  aktau: 'Актау',
  aksai: 'Аксай',
  kurchatov: 'Курчатов',
  priozersk: 'Приозерск',
  zyryanovsk: 'Зыряновск',
  serebryansk: 'Серебрянск',
  qazaly: 'Казалы',
  embi: 'Эмба',
  atbasar: 'Атбасар',
  ereimentau: 'Ерейментау',
  karkaralinsk: 'Каркаралинск',
  balkhash: 'Балхаш',
  karazhal: 'Каражал',
  abay: 'Абай',
  zaysan: 'Зайсан',
}

export const getCityName = (alias: string | null): string | null => {
  if (!alias) {
    return null;
  }
  return CITY_ALIASES[alias.toLowerCase()] || alias;
};
